### ISSUE TITLE
Cross-browser test

### ISSUE THREAD

**Issue by mhulse** [rgpages/popular#9]
Currently only tested in Firefox latest/Mac. Need to check all latest browsers for oddities.

Not going to worry about older browsers for this project.

**Comment by robertdenton** [comment]
IE9 doesn't load because of consoles? Maybe this could fix it: https://www.npmjs.com/package/grunt-remove-logging. Had to get rid of every mention of console from the js but it works on ie9 now.

**Comment by robertdenton** [comment]
Cross browsing successful. Closing.
